name: CD

on:
  push:
    tags:
      - '*'

  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: ['**']

jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment: 
      name: production
      url: https://jsr.io/@siguici/plugwind

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        deno-version: [1.44]

    name: 🚀 Deploy plugwind to JSR using Deno ${{ matrix.deno-version }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔨 Configure Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: 📦️ Download Deno distribution files
        uses: actions/download-artifact@v4
        with:
          name: deno_dist
          path: jsr
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📂 List distribution files
        run: ls -la jsr

      - name: 🚨 Fix code style
        run: deno task fix

      - name: 🚀 Publish to JSR
        run: deno run -A jsr:@david/publish-on-tag@0.1.4
